language: generic
services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ADDITIONAL_DEBS='apt-utils dialog curl wget'
    - AFTER_SCRIPT='rosenv sh .travis.xacro_test.sh'
    - CATKIN_LINT=pedantic
    - CMAKE_ARGS=-DCMAKE_BUILD_TYPE=Release
    - NOT_TEST_DOWNSTREAM=true
    - ROS_REPO=ros
    - VERBOSE_OUTPUT=false
    - VERBOSE_TESTS=false
  matrix:
    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=file
    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=debian
    - ROS_DISTRO=melodic UPSTREAM_WORKSPACE=file
    - ROS_DISTRO=melodic UPSTREAM_WORKSPACE=debian
    - ROS_DISTRO=noetic UPSTREAM_WORKSPACE=file
    - ROS_DISTRO=noetic UPSTREAM_WORKSPACE=debian
matrix:
  allow_failures:
    - env: ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=debian
    - env: ROS_DISTRO=melodic UPSTREAM_WORKSPACE=debian
    - env: ROS_DISTRO=noetic UPSTREAM_WORKSPACE=debian
install:
  - git clone --quiet --depth 1 https://github.com/fmessmer/industrial_ci.git .industrial_ci -b master_pylint
script:
  - .industrial_ci/travis.sh
